[Variables]
@include=#Scale#RoundPlayer + Visualizer.inc

[Bar1]
Meter = BitMap
MeasureName = MeasureBand19
MeterStyle = MeterVisualizer
TransformationMatrix = 0.97863;-0.04233;0.04233;0.99863;0;0
X = (206 * #Scale#)
Y = (15 * #Scale#)

[Bar2]
Meter = BitMap
MeasureName = MeasureBand17
MeterStyle = MeterVisualizer
TransformationMatrix = 0.99652;-0.12553;0.12553;0.99652;0;0
X = (179 * #Scale#)
Y = (31 * #Scale#)

[Bar3]
Meter = BitMap
MeasureName = MeasureBand18
MeterStyle = MeterVisualizer
TransformationMatrix = 0.97815;-0.21891;0.21891;0.97815;0;0
X = (155 * #Scale#)
Y = (48 * #Scale#)

[Bar4]
Meter = BitMap
MeasureName = MeasureBand15
MeterStyle = MeterVisualizer
TransformationMatrix = 0.95105;-0.30902;0.30902;0.95105;0;0
X = (130 * #Scale#)
Y = (63 * #Scale#)

[Bar5]
Meter = BitMap
MeasureName = MeasureBand13
MeterStyle = MeterVisualizer
TransformationMatrix = 0.91354;-0.40673;0.40673;0.91354;0;0
X = (102 * #Scale#)
Y = (76 * #Scale#)

[Bar6]
Meter = BitMap
MeasureName = MeasureBand12
MeterStyle = MeterVisualizer
TransformationMatrix = 0.87454;-0.49503;0.49503;0.87454;0;0
X = (74 * #Scale#)
Y = (85 * #Scale#)

[Bar7]
Meter = BitMap
MeasureName = MeasureBand10
MeterStyle = MeterVisualizer
TransformationMatrix = 0.86602;-0.5952;0.5952;0.86602;0;0
X = (44 * #Scale#)
Y = (87 * #Scale#)

[Bar8]
Meter = BitMap
MeasureName = MeasureBand8
MeterStyle = MeterVisualizer
TransformationMatrix = 0.77714;-0.65932;0.65932;0.77714;0;0
X = (16 * #Scale#)
Y = (93 * #Scale#)

[Bar9]
Meter = BitMap
MeasureName = MeasureBand6
MeterStyle = MeterVisualizer
TransformationMatrix = 0.70711;-0.72711;0.72711;0.70711;0;0
X = (-13 * #Scale#)
Y = (95 * #Scale#)

[Bar10]
Meter = BitMap
MeasureName = MeasureBand4
MeterStyle = MeterVisualizer
TransformationMatrix = 0.62932;-0.77714;0.77714;0.62932;0;0
X = (-42 * #Scale#)
Y = (95 * #Scale#)

[Bar11]
Meter = BitMap
MeasureName = MeasureBand4
MeterStyle = MeterVisualizer
TransformationMatrix = 0.54464;-0.82867;0.82867;0.54464;0;0
X = (-72 * #Scale#)
Y = (92 * #Scale#)

[Bar12]
Meter = BitMap
MeasureName = MeasureBand6
MeterStyle = MeterVisualizer
TransformationMatrix = 0.45399;-0.85101;0.85101;0.45399;0;0
X = (-103 * #Scale#)
Y = (90 * #Scale#)

[Bar13]
Meter = BitMap
MeasureName = MeasureBand8
MeterStyle = MeterVisualizer
TransformationMatrix = 0.40673;-0.98054;0.98054;0.40673;0;0
X = (-121 * #Scale#)
Y = (69 * #Scale#)

[Bar14]
Meter = BitMap
MeasureName = MeasureBand10
MeterStyle = MeterVisualizer
TransformationMatrix = 0.30901;-0.92655;0.92655;0.30901;0;0
X = (-155 * #Scale#)
Y = (68 * #Scale#)

[Bar15]
Meter = BitMap
MeasureName = MeasureBand12
MeterStyle = MeterVisualizer
TransformationMatrix = 0.20791;-0.97814;0.97814;0.20791;0;0
X = (-180 * #Scale#)
Y = (47 * #Scale#)

[Bar16]
Meter = BitMap
MeasureName = MeasureBand13
MeterStyle = MeterVisualizer
TransformationMatrix = 0.10453;-0.99452;0.99452;0.10453;0;0
X = (-205 * #Scale#)
Y = (28 * #Scale#)

[Bar17]
Meter = BitMap
MeasureName = MeasureBand15
MeterStyle = MeterVisualizer
TransformationMatrix = 0.03133;-0.99863;0.99863;0.03133;0;0
X = (-226 * #Scale#)
Y = (13 * #Scale#)

[Bar18]
Meter = BitMap
MeasureName = MeasureBand17
MeterStyle = MeterVisualizer
TransformationMatrix = -0.09233;-0.99863;0.99863;-0.09233;0;0
X = (-248 * #Scale#)
Y = (-15 * #Scale#)

[Bar19]
Meter = BitMap
MeasureName = MeasureBand19
MeterStyle = MeterVisualizer
TransformationMatrix = -0.16791;-0.97814;0.97814;-0.16791;0;0
X = (-267 * #Scale#)
Y = (-34 * #Scale#)

[Bar20]
Meter = BitMap
MeasureName = MeasureBand31
MeterStyle = MeterVisualizer
TransformationMatrix = -0.25901;-0.95105;0.95105;-0.25901;0;0
X = (-285 * #Scale#)
Y = (-59 * #Scale#)

[Bar21]
Meter = BitMap
MeasureName = MeasureBand29
MeterStyle = MeterVisualizer
TransformationMatrix = -0.35836;-0.93358;0.93358;-0.35836;0;0
X = (-294 * #Scale#)
Y = (-87 * #Scale#)

[Bar22]
Meter = BitMap
MeasureName = MeasureBand28
MeterStyle = MeterVisualizer
TransformationMatrix = -0.46673;-0.91354;0.91354;-0.46673;0;0
X = (-297 * #Scale#)
Y = (-117 * #Scale#)

[Bar23]
Meter = BitMap
MeasureName = MeasureBand27
MeterStyle = MeterVisualizer
TransformationMatrix = -0.54464;-0.83867;0.83867;-0.54464;0;0
X = (-312 * #Scale#)
Y = (-149 * #Scale#)

[Bar24]
Meter = BitMap
MeasureName = MeasureBand26
MeterStyle = MeterVisualizer
TransformationMatrix = -0.59778;-0.80901;0.80901;-0.59778;0;0
X = (-319 * #Scale#)
Y = (-166 * #Scale#)

[Bar25]
Meter = BitMap
MeasureName = MeasureBand25
MeterStyle = MeterVisualizer
TransformationMatrix = -0.66913;-0.74314;0.74314;-0.66913;0;0
X = (-324 * #Scale#)
Y = (-197 * #Scale#)

[Bar26]
Meter = BitMap
MeasureName = MeasureBand24
MeterStyle = MeterVisualizer
TransformationMatrix = -0.74314;-0.66913;0.66913;-0.74314;0;0
X = (-323 * #Scale#)
Y = (-230 * #Scale#)

[Bar27]
Meter = BitMap
MeasureName = MeasureBand23
MeterStyle = MeterVisualizer
TransformationMatrix = -0.80901;-0.58775;0.58775;-0.80901;0;0
X = (-318 * #Scale#)
Y = (-262 * #Scale#)

[Bar28]
Meter = BitMap
MeasureName = MeasureBand22
MeterStyle = MeterVisualizer
TransformationMatrix = -0.86602;-0.5;0.5;-0.86602;0;0
X = (-310 * #Scale#)
Y = (-294 * #Scale#)

[Bar29]
Meter = BitMap
MeasureName = MeasureBand29
MeterStyle = MeterVisualizer
TransformationMatrix = -0.91354;-0.40673;0.40673;-0.87354;0;0
TransformationMatrix = -0.91354;-0.40673;0.40673;-0.87354;0;0
X = (-303 * #Scale#)
Y = (-334 * #Scale#)

[Bar30]
Meter = BitMap
MeasureName = MeasureBand28
MeterStyle = MeterVisualizer
TransformationMatrix = -0.95458;-0.35836;0.35836;-0.95458;0;0
X = (-291 * #Scale#)
Y = (-337 * #Scale#)

[Bar31]
Meter = BitMap
MeasureName = MeasureBand21
MeterStyle = MeterVisualizer
TransformationMatrix = -0.99092;-0.25882;0.25882;-0.99092;0;0
X = (-274 * #Scale#)
Y = (-364 * #Scale#)

[Bar32]
Meter = BitMap
MeasureName = MeasureBand22
MeterStyle = MeterVisualizer
TransformationMatrix = -0.98769;-0.15643;0.15643;-0.98769;0;0
X = (-263 * #Scale#)
Y = (-396 * #Scale#)

[Bar33]
Meter = BitMap
MeasureName = MeasureBand23
MeterStyle = MeterVisualizer
TransformationMatrix = -0.99863;-0.05233;0.05233;-0.99863;0;0
X = (-241 * #Scale#)
Y = (-421 * #Scale#)

[Bar34]
Meter = BitMap
MeasureName = MeasureBand24
MeterStyle = MeterVisualizer
TransformationMatrix = -0.99863;0.04033;-0.04033;-0.99863;0;0
X = (-222 * #Scale#)
Y = (-442 * #Scale#)

[Bar35]
Meter = BitMap
MeasureName = MeasureBand25
MeterStyle = MeterVisualizer
TransformationMatrix = -0.98769;0.11643;-0.11643;-0.98769;0;0
X = (-207 * #Scale#)
Y = (-459 * #Scale#)

[Bar36]
Meter = BitMap
MeasureName = MeasureBand26
MeterStyle = MeterVisualizer
TransformationMatrix = -0.96592;0.25882;-0.25882;-0.96592;0;0
X = (-162 * #Scale#)
Y = (-482 * #Scale#)

[Bar37]
Meter = BitMap
MeasureName = MeasureBand27
MeterStyle = MeterVisualizer
TransformationMatrix = -0.95105;0.30902;-0.30902;-0.95105;0;0
X = (-153 * #Scale#)
Y = (-490 * #Scale#)

[Bar38]
Meter = BitMap
MeasureName = MeasureBand28
MeterStyle = MeterVisualizer
TransformationMatrix = -0.91354;0.40673;-0.40673;-0.91354;0;0
X = (-122 * #Scale#)
Y = (-503 * #Scale#)

[Bar39]
Meter = BitMap
MeasureName = MeasureBand29
MeterStyle = MeterVisualizer
TransformationMatrix = -0.86602;0.5;-0.5;-0.86602;0;0
X = (-89 * #Scale#)
Y = (-513 * #Scale#)

[Bar40]
Meter = BitMap
MeasureName = MeasureBand30
MeterStyle = MeterVisualizer
TransformationMatrix = -0.80901;0.58775;-0.58775;-0.80901;0;0
X = (-56 * #Scale#)
Y = (-520 * #Scale#)

[Bar41]
Meter = BitMap
MeasureName = MeasureBand31
MeterStyle = MeterVisualizer
TransformationMatrix = -0.74314;0.66913;-0.66913;-0.74314;0;0
X = (-22 * #Scale#)
Y = (-524 * #Scale#)

[Bar42]
Meter = BitMap
MeasureName = MeasureBand32
MeterStyle = MeterVisualizer
TransformationMatrix = -0.70711;0.70711;-0.70711;-0.70711;0;0
X = (-12 * #Scale#)
Y = (-524 * #Scale#)

[Bar43]
Meter = BitMap
MeasureName = MeasureBand33
MeterStyle = MeterVisualizer
TransformationMatrix = -0.62932;0.77714;-0.77714;-0.62932;0;0
X = (22 * #Scale#)
Y = (-522 * #Scale#)

[Bar44]
Meter = BitMap
MeasureName = MeasureBand34
MeterStyle = MeterVisualizer
TransformationMatrix = -0.54464;0.83867;-0.83867;-0.54464;0;0
X = (56 * #Scale#)
Y = (-517 * #Scale#)

[Bar45]
Meter = BitMap
MeasureName = MeasureBand35
MeterStyle = MeterVisualizer
TransformationMatrix = -0.45399;0.89101;-0.89101;-0.45399;0;0
X = (88 * #Scale#)
Y = (-509 * #Scale#)

[Bar46]
Meter = BitMap
MeasureName = MeasureBand36
MeterStyle = MeterVisualizer
TransformationMatrix = -0.35836;0.93358;-0.93358;-0.35836;0;0
X = (119 * #Scale#)
Y = (-497 * #Scale#)

[Bar47]
Meter = BitMap
MeasureName = MeasureBand37
MeterStyle = MeterVisualizer
TransformationMatrix = -0.30901;0.97105;-0.97105;-0.30901;0;0
X = (128 * #Scale#)
Y = (-482 * #Scale#)

[Bar48]
Meter = BitMap
MeasureName = MeasureBand38
MeterStyle = MeterVisualizer
TransformationMatrix = -0.20791;0.97814;-0.97814;-0.20791;0;0
X = (157 * #Scale#)
Y = (-474 * #Scale#)

[Bar49]
Meter = BitMap
MeasureName = MeasureBand39
MeterStyle = MeterVisualizer
TransformationMatrix = -0.10453;0.99452;-0.99452;-0.10453;0;0
X = (185 * #Scale#)
Y = (-455 * #Scale#)

[Bar50]
Meter = BitMap
MeasureName = MeasureBand40
MeterStyle = MeterVisualizer
TransformationMatrix = -0.02233;0.99863;-0.99863;-0.02233;0;0
X = (203 * #Scale#)
Y = (-439 * #Scale#)

[Bar51]
Meter = BitMap
MeasureName = MeasureBand41
MeterStyle = MeterVisualizer
TransformationMatrix = 0.08233;0.99863;-0.99863;0.08233;0;0
X = (226 * #Scale#)
Y = (-415 * #Scale#)

[Bar52]
Meter = BitMap
MeasureName = MeasureBand42
MeterStyle = MeterVisualizer
TransformationMatrix = 0.18791;0.97814;-0.97814;0.18791;0;0
X = (249 * #Scale#)
Y = (-390 * #Scale#)

[Bar53]
Meter = BitMap
MeasureName = MeasureBand43
MeterStyle = MeterVisualizer
TransformationMatrix = 0.26881;0.96592;-0.96592;0.26881;0;0
X = (259 * #Scale#)
Y = (-367 * #Scale#)

[Bar54]
Meter = BitMap
MeasureName = MeasureBand44
MeterStyle = MeterVisualizer
TransformationMatrix = 0.35836;0.93358;-0.93358;0.35836;0;0
X = (273 * #Scale#)
Y = (-341 * #Scale#)

[Bar55]
Meter = BitMap
MeasureName = MeasureBand45
MeterStyle = MeterVisualizer
TransformationMatrix = 0.45399;0.89101;-0.89101;0.45399;0;0
X = (286 * #Scale#)
Y = (-311 * #Scale#)

[Bar56]
Meter = BitMap
MeasureName = MeasureBand46
MeterStyle = MeterVisualizer
TransformationMatrix = 0.52464;0.83867;-0.83867;0.52464;0;0
X = (296 * #Scale#)
Y = (-287 * #Scale#)

[Bar57]
Meter = BitMap
MeasureName = MeasureBand47
MeterStyle = MeterVisualizer
TransformationMatrix = 0.58778;0.80901;-0.80901;0.58778;0;0
X = (293 * #Scale#)
Y = (-264 * #Scale#)

[Bar58]
Meter = BitMap
MeasureName = MeasureBand48
MeterStyle = MeterVisualizer
TransformationMatrix = 0.66913;0.74314;-0.74314;0.66913;0;0
X = (297 * #Scale#)
Y = (-231 * #Scale#)

[Bar59]
Meter = BitMap
MeasureName = MeasureBand49
MeterStyle = MeterVisualizer
TransformationMatrix = 0.74314;0.66913;-0.66913;0.74314;0;0
X = (298 * #Scale#)
Y = (-198 * #Scale#)

[Bar60]
Meter = BitMap
MeasureName = MeasureBand50
MeterStyle = MeterVisualizer
TransformationMatrix = 0.80901;0.58775;-0.58775;0.80901;0;0
X = (297 * #Scale#)
Y = (-166 * #Scale#)

[Bar61]
Meter = BitMap
MeasureName = MeasureBand44
MeterStyle = MeterVisualizer
TransformationMatrix = 0.86602;0.5;-0.5;0.86602;0;0
X = (292 * #Scale#)
Y = (-134 * #Scale#)

[Bar62]
Meter = BitMap
MeasureName = MeasureBand42
MeterStyle = MeterVisualizer
TransformationMatrix = 0.97101;0.45399;-0.45399;0.97101;0;0
X = (263 * #Scale#)
Y = (-103 * #Scale#)

[Bar63]
Meter = BitMap
MeasureName = MeasureBand40
MeterStyle = MeterVisualizer
TransformationMatrix = 0.90105;0.30902;-0.30902;0.90105;0;0
X = (285 * #Scale#)
Y = (-78 * #Scale#)

[Bar64]
Meter = BitMap
MeasureName = MeasureBand38
MeterStyle = MeterVisualizer
TransformationMatrix = 0.94592;0.25882;-0.25882;0.94592;0;0
X = (263 * #Scale#)
Y = (-60 * #Scale#)

[Bar65]
Meter = BitMap
MeasureName = MeasureBand36
MeterStyle = MeterVisualizer
TransformationMatrix = 0.98769;0.15643;-0.15643;0.98769;0;0
X = (241 * #Scale#)
Y = (-32 * #Scale#)

[Bar66]
Meter = BitMap
MeasureName = MeasureBand34
MeterStyle = MeterVisualizer
TransformationMatrix = 0.99863;0.05233;-0.05233;0.99863;0;0
X = (222 * #Scale#)
Y = (-6 * #Scale#)