[MeterBand1]
Meter = BitMap
MeasureName = MeasureBand19
MeterStyle = BandStyle
TransformationMatrix = 0.97863;-0.04233;0.04233;0.99863;0;0
X = (206*#Scale#)
Y = (9*#Scale#)

[MeterBand2]
Meter = BitMap
MeasureName = MeasureBand17
MeterStyle = BandStyle
TransformationMatrix = 0.99652;-0.12553;0.12553;0.99652;0;0
X = (179*#Scale#)
Y = (25*#Scale#)

[MeterBand3]
Meter = BitMap
MeasureName = MeasureBand18
MeterStyle = BandStyle
TransformationMatrix = 0.97815;-0.21891;0.21891;0.97815;0;0
X = (155*#Scale#)
Y = (42*#Scale#)

[MeterBand4]
Meter = BitMap
MeasureName = MeasureBand15
MeterStyle = BandStyle
TransformationMatrix = 0.95105;-0.30902;0.30902;0.95105;0;0
X = (130*#Scale#)
Y = (57*#Scale#)

[MeterBand5]
Meter = BitMap
MeasureName = MeasureBand13
MeterStyle = BandStyle
TransformationMatrix = 0.91354;-0.40673;0.40673;0.91354;0;0
X = (102*#Scale#)
Y = (70*#Scale#)

[MeterBand6]
Meter = BitMap
MeasureName = MeasureBand12
MeterStyle = BandStyle
TransformationMatrix = 0.87454;-0.49503;0.49503;0.87454;0;0
X = (74*#Scale#)
Y = (78*#Scale#)

[MeterBand7]
Meter = BitMap
MeasureName = MeasureBand10
MeterStyle = BandStyle
TransformationMatrix = 0.86602;-0.5952;0.5952;0.86602;0;0
X = (44*#Scale#)
Y = (77*#Scale#)

[MeterBand8]
Meter = BitMap
MeasureName = MeasureBand8
MeterStyle = BandStyle
TransformationMatrix = 0.77714;-0.65932;0.65932;0.77714;0;0
X = (16*#Scale#)
Y = (86*#Scale#)

[MeterBand9]
Meter = BitMap
MeasureName = MeasureBand6
MeterStyle = BandStyle
TransformationMatrix = 0.70711;-0.72711;0.72711;0.70711;0;0
X = (-13*#Scale#)
Y = (88*#Scale#)

[MeterBand10]
Meter = BitMap
MeasureName = MeasureBand4
MeterStyle = BandStyle
TransformationMatrix = 0.62932;-0.77714;0.77714;0.62932;0;0
X = (-42*#Scale#)
Y = (89*#Scale#)

[MeterBand11]
Meter = BitMap
MeasureName = MeasureBand4
MeterStyle = BandStyle
TransformationMatrix = 0.54464;-0.82867;0.82867;0.54464;0;0
X = (-72*#Scale#)
Y = (86*#Scale#)

[MeterBand12]
Meter = BitMap
MeasureName = MeasureBand6
MeterStyle = BandStyle
TransformationMatrix = 0.45399;-0.85101;0.85101;0.45399;0;0
X = (-103*#Scale#)
Y = (84*#Scale#)

[MeterBand13]
Meter = BitMap
MeasureName = MeasureBand8
MeterStyle = BandStyle
TransformationMatrix = 0.40673;-0.98054;0.98054;0.40673;0;0
X = (-121*#Scale#)
Y = (58*#Scale#)

[MeterBand14]
Meter = BitMap
MeasureName = MeasureBand10
MeterStyle = BandStyle
TransformationMatrix = 0.30901;-0.92655;0.92655;0.30901;0;0
X = (-155*#Scale#)
Y = (62*#Scale#)

[MeterBand15]
Meter = BitMap
MeasureName = MeasureBand12
MeterStyle = BandStyle
TransformationMatrix = 0.20791;-0.97814;0.97814;0.20791;0;0
X = (-180*#Scale#)
Y = (41*#Scale#)

[MeterBand16]
Meter = BitMap
MeasureName = MeasureBand13
MeterStyle = BandStyle
TransformationMatrix = 0.10453;-0.99452;0.99452;0.10453;0;0
X = (-205*#Scale#)
Y = (22*#Scale#)

[MeterBand17]
Meter = BitMap
MeasureName = MeasureBand15
MeterStyle = BandStyle
TransformationMatrix = 0.03133;-0.99863;0.99863;0.03133;0;0
X = (-226*#Scale#)
Y = (7*#Scale#)

[MeterBand18]
Meter = BitMap
MeasureName = MeasureBand17
MeterStyle = BandStyle
TransformationMatrix = -0.09233;-0.99863;0.99863;-0.09233;0;0
X = (-248*#Scale#)
Y = (-21*#Scale#)

[MeterBand19]
Meter = BitMap
MeasureName = MeasureBand19
MeterStyle = BandStyle
TransformationMatrix = -0.16791;-0.97814;0.97814;-0.16791;0;0
X = (-267*#Scale#)
Y = (-40*#Scale#)

[MeterBand20]
Meter = BitMap
MeasureName = MeasureBand31
MeterStyle = BandStyle
TransformationMatrix = -0.25901;-0.95105;0.95105;-0.25901;0;0
X = (-285*#Scale#)
Y = (-65*#Scale#)

[MeterBand21]
Meter = BitMap
MeasureName = MeasureBand29
MeterStyle = BandStyle
TransformationMatrix = -0.35836;-0.93358;0.93358;-0.35836;0;0
X = (-294*#Scale#)
Y = (-93*#Scale#)

[MeterBand22]
Meter = BitMap
MeasureName = MeasureBand28
MeterStyle = BandStyle
TransformationMatrix = -0.46673;-0.91354;0.91354;-0.46673;0;0
X = (-297*#Scale#)
Y = (-123*#Scale#)

[MeterBand23]
Meter = BitMap
MeasureName = MeasureBand27
MeterStyle = BandStyle
TransformationMatrix = -0.54464;-0.83867;0.83867;-0.54464;0;0
X = (-312*#Scale#)
Y = (-155*#Scale#)

[MeterBand24]
Meter = BitMap
MeasureName = MeasureBand26
MeterStyle = BandStyle
TransformationMatrix = -0.59778;-0.80901;0.80901;-0.59778;0;0
X = (-319*#Scale#)
Y = (-172*#Scale#)

[MeterBand25]
Meter = BitMap
MeasureName = MeasureBand25
MeterStyle = BandStyle
TransformationMatrix = -0.66913;-0.74314;0.74314;-0.66913;0;0
X = (-324*#Scale#)
Y = (-203*#Scale#)

[MeterBand26]
Meter = BitMap
MeasureName = MeasureBand24
MeterStyle = BandStyle
TransformationMatrix = -0.74314;-0.66913;0.66913;-0.74314;0;0
X = (-323*#Scale#)
Y = (-236*#Scale#)

[MeterBand27]
Meter = BitMap
MeasureName = MeasureBand23
MeterStyle = BandStyle
TransformationMatrix = -0.80901;-0.58775;0.58775;-0.80901;0;0
X = (-318*#Scale#)
Y = (-268*#Scale#)

[MeterBand28]
Meter = BitMap
MeasureName = MeasureBand22
MeterStyle = BandStyle
TransformationMatrix = -0.86602;-0.5;0.5;-0.86602;0;0
X = (-310*#Scale#)
Y = (-300*#Scale#)

[MeterBand29]
Meter = BitMap
MeasureName = MeasureBand29
MeterStyle = BandStyle
TransformationMatrix = -0.91354;-0.40673;0.40673;-0.87354;0;0
TransformationMatrix = -0.91354;-0.40673;0.40673;-0.87354;0;0
X = (-303*#Scale#)
Y = (-340*#Scale#)

[MeterBand30]
Meter = BitMap
MeasureName = MeasureBand28
MeterStyle = BandStyle
TransformationMatrix = -0.95458;-0.35836;0.35836;-0.95458;0;0
X = (-291*#Scale#)
Y = (-343*#Scale#)

[MeterBand31]
Meter = BitMap
MeasureName = MeasureBand21
MeterStyle = BandStyle
TransformationMatrix = -0.99092;-0.25882;0.25882;-0.99092;0;0
X = (-274*#Scale#)
Y = (-370*#Scale#)

[MeterBand32]
Meter = BitMap
MeasureName = MeasureBand22
MeterStyle = BandStyle
TransformationMatrix = -0.98769;-0.15643;0.15643;-0.98769;0;0
X = (-263*#Scale#)
Y = (-402*#Scale#)

[MeterBand33]
Meter = BitMap
MeasureName = MeasureBand23
MeterStyle = BandStyle
TransformationMatrix = -0.99863;-0.05233;0.05233;-0.99863;0;0
X = (-241*#Scale#)
Y = (-427*#Scale#)

[MeterBand34]
Meter = BitMap
MeasureName = MeasureBand24
MeterStyle = BandStyle
TransformationMatrix = -0.99863;0.04033;-0.04033;-0.99863;0;0
X = (-222*#Scale#)
Y = (-448*#Scale#)

[MeterBand35]
Meter = BitMap
MeasureName = MeasureBand25
MeterStyle = BandStyle
TransformationMatrix = -0.98769;0.11643;-0.11643;-0.98769;0;0
X = (-207*#Scale#)
Y = (-465*#Scale#)

[MeterBand36]
Meter = BitMap
MeasureName = MeasureBand26
MeterStyle = BandStyle
TransformationMatrix = -0.96592;0.25882;-0.25882;-0.96592;0;0
X = (-162*#Scale#)
Y = (-488*#Scale#)

[MeterBand37]
Meter = BitMap
MeasureName = MeasureBand27
MeterStyle = BandStyle
TransformationMatrix = -0.95105;0.30902;-0.30902;-0.95105;0;0
X = (-153*#Scale#)
Y = (-496*#Scale#)

[MeterBand38]
Meter = BitMap
MeasureName = MeasureBand28
MeterStyle = BandStyle
TransformationMatrix = -0.91354;0.40673;-0.40673;-0.91354;0;0
X = (-122*#Scale#)
Y = (-509*#Scale#)

[MeterBand39]
Meter = BitMap
MeasureName = MeasureBand29
MeterStyle = BandStyle
TransformationMatrix = -0.86602;0.5;-0.5;-0.86602;0;0
X = (-89*#Scale#)
Y = (-519*#Scale#)

[MeterBand40]
Meter = BitMap
MeasureName = MeasureBand30
MeterStyle = BandStyle
TransformationMatrix = -0.80901;0.58775;-0.58775;-0.80901;0;0
X = (-56*#Scale#)
Y = (-526*#Scale#)

[MeterBand41]
Meter = BitMap
MeasureName = MeasureBand31
MeterStyle = BandStyle
TransformationMatrix = -0.74314;0.66913;-0.66913;-0.74314;0;0
X = (-22*#Scale#)
Y = (-530*#Scale#)

[MeterBand42]
Meter = BitMap
MeasureName = MeasureBand32
MeterStyle = BandStyle
TransformationMatrix = -0.70711;0.70711;-0.70711;-0.70711;0;0
X = (-12*#Scale#)
Y = (-530*#Scale#)

[MeterBand43]
Meter = BitMap
MeasureName = MeasureBand33
MeterStyle = BandStyle
TransformationMatrix = -0.62932;0.77714;-0.77714;-0.62932;0;0
X = (22*#Scale#)
Y = (-528*#Scale#)

[MeterBand44]
Meter = BitMap
MeasureName = MeasureBand34
MeterStyle = BandStyle
TransformationMatrix = -0.54464;0.83867;-0.83867;-0.54464;0;0
X = (56*#Scale#)
Y = (-523*#Scale#)

[MeterBand45]
Meter = BitMap
MeasureName = MeasureBand35
MeterStyle = BandStyle
TransformationMatrix = -0.45399;0.89101;-0.89101;-0.45399;0;0
X = (88*#Scale#)
Y = (-515*#Scale#)

[MeterBand46]
Meter = BitMap
MeasureName = MeasureBand36
MeterStyle = BandStyle
TransformationMatrix = -0.35836;0.93358;-0.93358;-0.35836;0;0
X = (119*#Scale#)
Y = (-503*#Scale#)

[MeterBand47]
Meter = BitMap
MeasureName = MeasureBand37
MeterStyle = BandStyle
TransformationMatrix = -0.30901;0.97105;-0.97105;-0.30901;0;0
X = (128*#Scale#)
Y = (-488*#Scale#)

[MeterBand48]
Meter = BitMap
MeasureName = MeasureBand38
MeterStyle = BandStyle
TransformationMatrix = -0.20791;0.97814;-0.97814;-0.20791;0;0
X = (157*#Scale#)
Y = (-480*#Scale#)

[MeterBand49]
Meter = BitMap
MeasureName = MeasureBand39
MeterStyle = BandStyle
TransformationMatrix = -0.10453;0.99452;-0.99452;-0.10453;0;0
X = (185*#Scale#)
Y = (-461*#Scale#)

[MeterBand50]
Meter = BitMap
MeasureName = MeasureBand40
MeterStyle = BandStyle
TransformationMatrix = -0.02233;0.99863;-0.99863;-0.02233;0;0
X = (203*#Scale#)
Y = (-445*#Scale#)

[MeterBand51]
Meter = BitMap
MeasureName = MeasureBand41
MeterStyle = BandStyle
TransformationMatrix = 0.08233;0.99863;-0.99863;0.08233;0;0
X = (226*#Scale#)
Y = (-421*#Scale#)

[MeterBand52]
Meter = BitMap
MeasureName = MeasureBand42
MeterStyle = BandStyle
TransformationMatrix = 0.18791;0.97814;-0.97814;0.18791;0;0
X = (249*#Scale#)
Y = (-396*#Scale#)

[MeterBand53]
Meter = BitMap
MeasureName = MeasureBand43
MeterStyle = BandStyle
TransformationMatrix = 0.26881;0.96592;-0.96592;0.26881;0;0
X = (259*#Scale#)
Y = (-373*#Scale#)

[MeterBand54]
Meter = BitMap
MeasureName = MeasureBand44
MeterStyle = BandStyle
TransformationMatrix = 0.35836;0.93358;-0.93358;0.35836;0;0
X = (273*#Scale#)
Y = (-347*#Scale#)

[MeterBand55]
Meter = BitMap
MeasureName = MeasureBand45
MeterStyle = BandStyle
TransformationMatrix = 0.45399;0.89101;-0.89101;0.45399;0;0
X = (286*#Scale#)
Y = (-317*#Scale#)

[MeterBand56]
Meter = BitMap
MeasureName = MeasureBand46
MeterStyle = BandStyle
TransformationMatrix = 0.52464;0.83867;-0.83867;0.52464;0;0
X = (296*#Scale#)
Y = (-293*#Scale#)

[MeterBand57]
Meter = BitMap
MeasureName = MeasureBand47
MeterStyle = BandStyle
TransformationMatrix = 0.58778;0.80901;-0.80901;0.58778;0;0
X = (293*#Scale#)
Y = (-270*#Scale#)

[MeterBand58]
Meter = BitMap
MeasureName = MeasureBand48
MeterStyle = BandStyle
TransformationMatrix = 0.66913;0.74314;-0.74314;0.66913;0;0
X = (297*#Scale#)
Y = (-237*#Scale#)

[MeterBand59]
Meter = BitMap
MeasureName = MeasureBand49
MeterStyle = BandStyle
TransformationMatrix = 0.74314;0.66913;-0.66913;0.74314;0;0
X = (298*#Scale#)
Y = (-204*#Scale#)

[MeterBand60]
Meter = BitMap
MeasureName = MeasureBand50
MeterStyle = BandStyle
TransformationMatrix = 0.80901;0.58775;-0.58775;0.80901;0;0
X = (297*#Scale#)
Y = (-172*#Scale#)

[MeterBand61]
Meter = BitMap
MeasureName = MeasureBand44
MeterStyle = BandStyle
TransformationMatrix = 0.86602;0.5;-0.5;0.86602;0;0
X = (292*#Scale#)
Y = (-140*#Scale#)

[MeterBand62]
Meter = BitMap
MeasureName = MeasureBand42
MeterStyle = BandStyle
TransformationMatrix = 0.97101;0.45399;-0.45399;0.97101;0;0
X = (263*#Scale#)
Y = (-114*#Scale#)

[MeterBand63]
Meter = BitMap
MeasureName = MeasureBand40
MeterStyle = BandStyle
TransformationMatrix = 0.90105;0.30902;-0.30902;0.90105;0;0
X = (285*#Scale#)
Y = (-84*#Scale#)

[MeterBand64]
Meter = BitMap
MeasureName = MeasureBand38
MeterStyle = BandStyle
TransformationMatrix = 0.94592;0.25882;-0.25882;0.94592;0;0
X = (263*#Scale#)
Y = (-66*#Scale#)

[MeterBand65]
Meter = BitMap
MeasureName = MeasureBand36
MeterStyle = BandStyle
TransformationMatrix = 0.98769;0.15643;-0.15643;0.98769;0;0
X = (241*#Scale#)
Y = (-38*#Scale#)

[MeterBand66]
Meter = BitMap
MeasureName = MeasureBand34
MeterStyle = BandStyle
TransformationMatrix = 0.99863;0.05233;-0.05233;0.99863;0;0
X = (222*#Scale#)
Y = (-12*#Scale#)